const settings = [
{
  "MongoDB":
  {
      "server": "https://eu-central-1.aws.data.mongodb-api.com/app/sprt-bvzmi/endpoint/documents",
      "login_url": "https://eu-central-1.aws.realm.mongodb.com/api/client/v2.0/app/",
      "app_id": "sprt-zzhhc",
      "dev_app_id":"sprt-bvzmi",
      "prod_app_id":"sprt-zzhhc",
      "secret" : "uHi6L3zGigVv6V2",
      "webhooks" : {
        "search" : "search",
        "getDoc" : "getdocbyid",
        "update" : "update",
        "insert" : "insert",
        "delete" : "delete",
        "getLastInsertedDocument" : "getLastInsertedDocument",
        "collectionCount" : "collectionCount",
      }
  },
  "Fields":
  {
    "DOCN" : "Document Number",
    "TITL" : "Titel",
    "UDAT" : "Udsendelsesdato",
    "RDAT" : "RDAT",
    "BAGR" : "Baggrund",
    "KEYW" : "Emneord",
    "BNNA" : "Båndnummer A",
    "BNTA" : "Båndtype A",
    "BNFA" : "Båndformat A",
    "LYDA" : "Lyd A",
    "BEMK" : "Bemærk",
    "ID"   : "ID",
    "STAT" : "Stat",
    "BNNB" : "Båndnummer B",
    "BNTB" : "Båndtype B",
    "BNFB" : "Båndformat B",
    "LYDB" : "Lyd B",
    "TVST" : "TV Station",
    "IDAT" : "IDAT",
    "OPHV" : "Reporter",
    "BBSK" : "Billedbeskrivelse",
    "MEDV" : "Medvirkende",
    "LOKA" : "Lokalitet",
    "BNNC" : "Båndnummer C",
    "BNTC" : "Båndtype C",
    "BNFC" : "Båndformat C",
    "LYDC" : "Lyd C",
    "LYDD" : "Lyd D",
    "VARG" : "VARG",
    "HYLB" : "HYLB",
    "TIDB" : "TIDB",
    "FOGR" : "FOGR",
    "BNND" : "Båndnummer D",
    "BNTD" : "Båndtype D",
    "BNFD" : "Båndformat D",
    "BNNE" : "Båndnummer E",
    "BNTE" : "Båndtype E",
    "BNFE" : "Båndformat E",
    "HYLA" : "HYLA",
    "TIDC" : "TIDC",
    "TIDA" : "TIDA",
    "HYLC" : "HYLC",
    "TIDD" : "TIDD",
    "LYDE" : "LYDE",
    "HYLD" : "HYLD",
    "BDAT" : "BDAT",
    "RAAB" : "RAAB",
    "HYLE" : "HYLE",
    "BNNF" : "Båndnummer F",
    "BNTF" : "Båndtype F",
    "BNFF" : "Båndformat F",
    "LYDF" : "Lyd F",
    "TIDE" : "TIDE",
    "HUSN" : "Husnummer",
    "BNNG" : "Båndnummer G",
    "BNTG" : "Båndtype G",
    "BNFG" : "Båndformat G",
    "BNNH" : "Båndnummer H",
    "BNTH" : "Båndtype H",
    "BNFH" : "Båndformat H",
    "LYDG" : "Lyd G",
    "LYDH" : "Lyd H",
    "HYLF" : "HYLF",
    "TIDF" : "TIDF",
    "HYLG" : "HYLG",
    "TIDG" : "TIDG",
    "HYLH" : "HYLH",
    "TIDH" : "TIDH"
  }
}
]

export default settings
